const ACTION_TYPES = {
  // page actioins
  HOMEPAGE: 'HOMEPAGE',
  TASKPAGE: 'TASKPAGE',
  // task actions basics
  // CREATE_TASK: 'CREATE_TASK',
  // GET_ALL_TASKS: 'GET_ALL_TASKS',
  // GET_TASK: 'GET_TASK',
  // UPDATE_TASK: 'UPDATE_TASK',
  // DELETE_TASK: 'DELETE_TASK',

  // task actions advanced
  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',

  GET_ALL_TASKS_REQUEST: 'GET_ALL_TASKS_REQUEST',
  GET_ALL_TASKS_SUCCESS: 'GET_ALL_TASKS_SUCCESS',
  GET_ALL_TASKS_ERROR: 'GET_ALL_TASKS_ERROR',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',

  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',

};

export default ACTION_TYPES;
